// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqRJcZv2XOuRsbPgqjsv02i0OYvklfI0',
    appId: '1:566979228305:web:3cb1de5e119f515f100530',
    messagingSenderId: '566979228305',
    projectId: 'emoji-1cece',
    authDomain: 'emoji-1cece.firebaseapp.com',
    storageBucket: 'emoji-1cece.appspot.com',
    measurementId: 'G-EQ8XNWRTRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdtT95gMCcP8avQOy9nPMhIpZIyj7FHqw',
    appId: '1:566979228305:android:d75d17916b99d63e100530',
    messagingSenderId: '566979228305',
    projectId: 'emoji-1cece',
    storageBucket: 'emoji-1cece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKBEAMY8olPfzvHbM7DfyhnTVRL9C-Pw',
    appId: '1:566979228305:ios:2c48cb12c1dea6aa100530',
    messagingSenderId: '566979228305',
    projectId: 'emoji-1cece',
    storageBucket: 'emoji-1cece.appspot.com',
    iosClientId: '566979228305-pde8sovsgq9d4t90aof1cm5t6747l5d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.emoji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKBEAMY8olPfzvHbM7DfyhnTVRL9C-Pw',
    appId: '1:566979228305:ios:e7ace167b7c46adc100530',
    messagingSenderId: '566979228305',
    projectId: 'emoji-1cece',
    storageBucket: 'emoji-1cece.appspot.com',
    iosClientId: '566979228305-9geg8hs36bl8c2mce5tvjucui5qll386.apps.googleusercontent.com',
    iosBundleId: 'com.example.emoji.RunnerTests',
  );
}
